services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped

  prediction:
    build:
      context: ./prediction
      args:
        ARCH: ""
    ports:
      - "9000:9000"
    env_file:
      - .env
    restart: unless-stopped
