services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    environment:
      - PREDICTION_URL=http://prediction:9000/detect
    env_file:
      - .env
    restart: unless-stopped

  prediction:
    build:
      context: ./prediction
      args:
        ARCH: ""
    env_file:
      - .env
    restart: unless-stopped
