version: "2"

services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    env_file:
      - .env
  prediction:
    build: ./prediction
    ports:
      - "9000:9000"
    env_file:
      - .env
